export const TEST_CALL_API = 'TEST_CALL_API';
export const GET_TOKEN_LOGIN = 'GET_TOKEN_LOGIN';
export const VERIFY_TOKEN_FOR_GET_INFO = 'VERIFY_TOKEN_FOR_GET_INFO';
export const GET_ALL_COURSE = 'GET_ALL_COURSE';
export const QUERY_REGISTER_PRETEACHER = 'QUERY_REGISTER_PRETEACHER';

export const QUERY_GET_LIST_CLASS = 'QUERY_GET_LIST_CLASS';
export const QUERY_GET_LIST_TIME_SCHEDULE = 'QUERY_GET_LIST_TIME_SCHEDULE';

export const QUERY_GET_LIST_COURSE = 'QUERY_GET_LIST_COURSE';

export const QUERY_CREATE_CLASS = 'QUERY_CREATE_CLASS';

export const QUERY_GET_LOCATIONS = 'QUERY_GET_LOCATIONS';

export const QUERY_GET_CURRENT_DATA_BOOK_TEACHER = 'QUERY_GET_CURRENT_DATA_BOOK_TEACHER';
export const QUERY_ADD_DATA_BOOK_TEACHER = 'QUERY_ADD_DATA_BOOK_TEACHER';

export const QUERY_DETAIL_CLASS = 'QUERY_DETAIL_CLASS';

export const QUERY_FIND_TEACHER_BY_EMAIL = 'QUERY_FIND_TEACHER_BY_EMAIL';

export const QUERY_HANDLE_TEACHER_IN_RECORD_BT = 'QUERY_HANDLE_TEACHER_IN_RECORD_BT';

export const QUERY_CLASS_SESSION = 'QUERY_CLASS_SESSION';

export const QUERY_UPDATE_CLASS_BASIC_INFOR = 'QUERY_UPDATE_CLASS_BASIC_INFOR';

export const QUERY_GET_LIST_TEACHER = 'QUERY_GET_LIST_TEACHER';
export const QUERY_TEACHER_REGISTER_COURSE = 'QUERY_TEACHER_REGISTER_COURSE';
export const QUERY_TEACHER_SCHEDULE = 'QUERY_TEACHER_SCHEDULE';

export const QUERY_GET_ATTENDANCE_TEACHER = 'QUERY_GET_ATTENDANCE_TEACHER';

export const QUERY_GET_LIST_CLASS_FEEDBACK_ACTION = 'QUERY_GET_LIST_CLASS_FEEDBACK_ACTION';

export const QUERY_UPDATE_CLASS_FEEDBACK = 'QUERY_UPDATE_CLASS_FEEDBACK';

export const QUERY_GET_LIST_CLASS_IN_FEEDBACK = 'QUERY_GET_LIST_CLASS_IN_FEEDBACK';
export const QUERY_GET_LIST_GROUP_CLASS_IN_FEEDBACK = 'QUERY_GET_LIST_GROUP_CLASS_IN_FEEDBACK';
export const QUERY_RESPONSE_FEEDBACK = 'QUERY_RESPONSE_FEEDBACK';
export const QUERY_GET_LIST_RESPONSE_FEEDBACK = 'QUERY_GET_LIST_RESPONSE_FEEDBACK';