export const TEST_CALL_API = 'TEST_CALL_API';
export const GET_TOKEN_LOGIN = 'GET_TOKEN_LOGIN';
export const VERIFY_TOKEN_FOR_GET_INFO = 'VERIFY_TOKEN_FOR_GET_INFO';
export const GET_ALL_COURSE = 'GET_ALL_COURSE';
export const QUERY_REGISTER_PRETEACHER = 'QUERY_REGISTER_PRETEACHER';

export const QUERY_GET_LIST_CLASS = 'QUERY_GET_LIST_CLASS';