name: Deploy to Azure DevOps

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push code to Azure DevOps
      run: |
        git remote add azure https://cuongnv@mindx.com.vn:iqrlsy552hvopz64rbnbxqhjzhux4rkq6sige2mssosfylq5iriq@techkids.visualstudio.com/mindx-tms/_git/mindx-tms-web-app
        git push azure master